### ISSUE TITLE
How to get prediction probability for decision making based on some threshold

### ISSUE THREAD

**Issue by sujit420** [HeroResearchGroup/SmartSVM#1]
how do I get the prediction probability for classes? I may need it when I need to decide based on scoring like any other multiclass classification.
@oskarsinger, please help

**Comment by sujit420** [comment]
+ @GjjvdBurg @boselio @careymrz

**Comment by GjjvdBurg** [comment]
Hi @sujit420! Thanks for checking out SmartSVM and apologies for the slow response. I've added the ``predict_proba`` function to SmartSVM now. See the README for an example. This only works if the underlying binary classifier supports the ``predict_proba`` method as well. Hope this helps!

I'm closing this issue, but if you have further questions feel free to reopen.
